### ISSUE TITLE
Spaces after commas and periods removed from prompt message

### ISSUE THREAD

**Issue by allenbaron** [jeroen/askpass#5]
On Mac OS the following function call produces a prompt with a space missing after the period and comma (the text is just there to make identifying missing spaces easier).

`askpass::askpass("Each; symbol: should. have- a? space( after) it, do[ they")`

RETURNS the following prompt:

<img width="384" alt="Screen Shot 2021-11-29 at 2 52 13 PM" src="https://user-images.githubusercontent.com/21225409/143933446-5c0ca8e0-d37e-45e4-9d3d-3341bd02d040.png">

## Session Info
```
R version 4.1.1 (2021-08-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 11.6.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.1.1 tools_4.1.1    askpass_1.1
```

**Comment by jeroen** [comment]
This seems to be a bug/feature in rstudio. The askpass package simply calls the rstudio password UI. You can reproduce this same issue in rstudio without askpass:

```r
getOption('askpass')("test, test")
```

So if you want it fixed you need to report it at the IDE team.

**Comment by allenbaron** [comment]
I forgot to test the IDE effects. Thanks.
