### ISSUE TITLE
askpass does not return a character in interactive session in radian

### ISSUE THREAD

**Issue by duccioa** [jeroen/askpass#6]
Hello,
I am not sure this is a [radian](https://github.com/randy3k/radian) or askpass bug.

I am on a Ubuntu machine with R 4.1.2.

Let's take this simple code:

```R
library(askpass)
pwd = askpass("Pwd pls: ")
# Type 123 at the prompt
class(pwd)
```
If I open the terminal, start R and run the code above, pwd is returned as a character '123'.

```
> pwd
[1] "123"

```

If I start *radian* and run the code above the result is:

```
r$> pwd
<pointer: 0x7f03f38a6e40>
attr(,"class")
[1] "PyObject"
attr(,"convert")
[1] FALSE

```

Thank you

**Comment by duccioa** [comment]
The problem seems to stem from the option "askpass".

In radian:
```
r$> library(askpass)

r$> getOption("askpass")
function (...) 
.Call("_libR_xptr_callback", pointer, list(...), FALSE, FALSE)
<environment: 0x55b21de46c08>
attr(,"py_object")
<pointer: 0x7fb251520d80>
attr(,"class")
[1] "PyObject"
attr(,"class")
[1] "PyCallable" "PyObject"  

```
So the option "askpass" is set on this function instead of `ask_password_default()`. 
If I call `debug(askpass)` and replace the variable FUN with `ask_password_default()`, then it behaves as it should be.

**Comment by jeroen** [comment]
WHy does radian set `askpass` to something that does not work? I think this is a radian bug? Whatever radion sets as the `askpass` function should be returning a string...

**Comment by duccioa** [comment]
After your comment, I checked that the same behavior happens without loading `library(askpass)`.
I was mistakenly thinking that it was {askpass} that was setting the option "askpass" when loaded.
So, it does look like a radian bug.

**Comment by duccioa** [comment]
This issue has been fixed in https://github.com/randy3k/radian/commit/bcc43e69765f58ace478028a193fce541c32abf8
