### ISSUE TITLE
askpass CRAN package for R 4.2 triggering Deep Instinct virus protection

### ISSUE THREAD

**Issue by nm-dcs** [jeroen/askpass#8]
Hi,

We cannot install askpass 1.1 on R 4.2 because it is triggering Deep Instinct virus protection. The 1.1 version in the 4.1 CRAN repo does not trigger Deep Instinct.

Appreciate this might be an "us problem" but the askpass package for R 4.1.x and R 4.2.x are substantially different in size:

```
(base) dan@dan:~/askpass$ wget https://cran.rstudio.com/bin/windows/contrib/4.1/askpass_1.1.zip -P 4.1/
(base) dan@dan:~/askpass$ wget https://cran.rstudio.com/bin/windows/contrib/4.2/askpass_1.1.zip -P 4.2/
(base) dan@dan:~/askpass$ md5sum 4.1/askpass_1.1.zip
1085ac2407a4c10110bbdaf4532280d2  4.1/askpass_1.1.zip
(base) dan@dan:~/askpass$ md5sum 4.2/askpass_1.1.zip
1b1d7a8bcb6ff5dcca0f6e3ae01042ba  4.2/askpass_1.1.zip
(base) dan@dan:~/askpass$ ls -l 4.1/askpass_1.1.zip
-rw-rw-r-- 1 dan dan 243673 Jan  3 17:41 4.1/askpass_1.1.zip
(base) dan@dan:~/askpass$ ls -l 4.2/askpass_1.1.zip
-rw-rw-r-- 1 dan dan 72274 Jan  8 22:13 4.2/askpass_1.1.zip
```

Just flagging as an FYI

**Comment by nm-dcs** [comment]
Specifically it is:  `win-askpass64.exe` that is causing the issue

```
(base) dan@dan:~/askpass$ md5sum 4.1/askpass/win-askpass64.exe
1e1f9eeec8546800036910c877d36943  4.1/askpass/win-askpass64.exe
(base) dan@dan:~/askpass$ md5sum 4.2/askpass/win-askpass64.exe
088aa31a3776daa1a4cdabe1ccc50155  4.2/askpass/win-askpass64.exe
```

**Comment by jeroen** [comment]
The 4.1 and 4.2 versions are built with different compilers (rtools4 vs rtools42) so they are not going to be identical. Also the 4.1 version contains both 32-bit and 64-bit binaries, but as of 4.2 R has dropped 32-bit, that is why they are smaller.

I have no idea why your av flags it.

**Comment by nm-dcs** [comment]
Thanks Jeroen, I will pick it up with the vendor/IT.

**Comment by nm-dcs** [comment]
To close the loop, this is ultra specific to our AV. Have confirmed this is not flagged by most other common AV systems, we've introduced an exception for this binary.
